#!/bin/bash

# This Laminar before script implements *project* based workspaces and 
# environment variables. 

# We use the suggestion provided by issue #124 see: 
#   https://github.com/ohwgiles/laminar/issues/124#issuecomment-636382799 

# Get the project name by stripping everything after the dash from the job 
# name 
#
if [[ $JOB == *"-"* ]] ; then
  export PROJECT=${JOB%%-*}
else 
  export PROJECT="default"
fi
#
export PWORKSPACE=$LAMINAR_HOME/workspaces/$PROJECT
laminarc set PROJECT=$PROJECT
laminarc set PWORKSPACE=$PWORKSPACE
#
echo setting PROJECT to $PROJECT
echo setting PWORKSPACE to $PWORKSPACE
#
mkdir -p $PWORKSPACE

# Apply each environment variable declared in the project conf file
#
CONF=$LAMINAR_HOME/cfg/jobs/${PROJECT}.conf
if test -r $CONF ; then
  while read -r line; do
    if test -n "${line%%#*}" ; then
      echo laminarc set ${line%%#*};
      laminarc set ${line%%#*};
    fi
  done < $CONF
fi

# Apply each environment variable declared in the project env file
#
ENV=$LAMINAR_HOME/cfg/jobs/${PROJECT}.env
if test -r $ENV ; then
  while read -r line; do
    if test -n "${line%%#*}" ; then
      echo laminarc set ${line%%#*};
      laminarc set ${line%%#*};
    fi
   done < $ENV
fi

# Ensure the DIST evnvironment variable is set to a sane value
#
if test -z "$DIST" ; then
  export DIST=bionic
fi
#
laminarc set DIST=$DIST
#
echo setting DIST to $DIST
#
mkdir -p $PWORKSPACE/$DIST
