#!/bin/bash

# This bash scritp automates the installation of the Laminar-scripts.


source laminar.conf

export CFG_DIR=$LAMINAR_HOME/cfg
export JOB_DIR=$LAMINAR_HOME/cfg/jobs
export SCP_DIR=$LAMINAR_HOME/cfg/scripts

export BIN_DIR=$HOME/bin

mkdir -p $BIN_DIR
cp bin/startLaminar*           $BIN_DIR
cp bin/abortLaminar*           $BIN_DIR
cp bin/clearLaminar*           $BIN_DIR
cp bin/getLaminar*             $BIN_DIR

mkdir -p $CFG_DIR
cp cfgs/before                 $CFG_DIR

mkdir -p $JOB_DIR
cp jobs/podmanExample.run      $JOB_DIR
cp jobs/hello.run              $JOB_DIR
cp jobs/buildPodman*Base.run   $JOB_DIR 

mkdir -p $SCP_DIR
cp scripts/setupLaminarVars    $SCP_DIR

ln -fs $LAMINAR_BIN/laminarc   $BIN_DIR/laminarc
