#!/bin/bash

# This bash script runs a docker run command in a specified docker 
# container AND runs as the *dev* user. 

dumb-init -v -- docker run --rm -i \
  -v $LAMINAR_HOME:$LAMINAR_HOME   \
  -u dev:dev                       \
  -w "/home/dev"                   \
  $*
