#!/bin/bash

# This bash script runs a docker run command in a specified docker 
# container AND runs as the *dev* user. 

dumb-init -v -- docker run --rm -i             \
  -v $PWD:/home/dev                            \
  -v $PWORKSPACE/$DIST:/workspace              \
  -v $ARCHIVE:/archive                         \
  -u dev:dev                                   \
  -w "/home/dev"                               \
  $*
