#!/bin/bash

# This bash script sets the default values for the extra Laminar 
# environment variables 

if test -z "$DIST" ; then
  echo setting DIST to bionic
  export DIST=bionic
fi

if test -z "$PWORKSPACE" ; then
  echo setting PWORKSPACE to /home/dev/laminar/tasks/workspaces
  export PWORKSPACE=/home/dev/laminar/tasks/workspaces
fi

mkdir -p $PWORKSPACE/$DIST

